### PR TITLE
Added tidyverse-gpu folder - rocker/tidyverse + GPU (CUDA)

### PR DESCRIPTION
**Pull request by seabbs**
Hi, 

Added my attempt at GPU support for a rocker/tidyverse container as per seabbs/tidyverse-gpu#1

Everything seems to be in order based on [my current](https://www.samabbott.co.uk/post/benchmarking-workstation-xgboost/) - not exhaustive -  testing. Happy to make any changes suggested. 

Thanks 

Sam

### CODE REVIEW

**Comment by cboettig** [comment]
@seabbs Thanks, this is great.

**Comment by cboettig** [comment]
@seabbs whoops!  got my threads crossed, the previous comment (now deleted to avoid confusion) was meant for Noam's PR. I need a bigger screen so I can see where I'm typing!

**Comment by cboettig** [comment]
@seabbs Thanks for the PR!  Just wanted to get your take on preferred tags that you think would make it easiest to for users to find this image.  In the spirit of streamlining our stack  & minimizing confusion, I think it would make sense to have this as the primary GPU / ML image. Do you prefer as a Docker tag:

- `rocker/gpu`
-  `rocker/ml`
- `rocker/tidy-gpu`
- ... something else?

@eddelbuettel thoughts? (Sam's version is basically an update to the recipe that currently sits in the `gpu` dir here and is the only one built on hub, as `rocker/ml:gpu`, but I think it's confusing to use tags for both versions and flavors).

**Comment by seabbs** [comment]
Something that included `gpu` would probably be best to make it clear what it enables. 

Just a note: The Dockerfile as it currently stands does not install `keras` or `tensorflow` - unlike the current one in the `gpu` repo.

**Comment by eddelbuettel** [comment]
I have no strong feelings on naming. If it combines the *verse and gpu then maybe both should in the name too?

It may make sense to also layer keras and tf either in the same container or an additional one.

**Comment by cboettig** [comment]
@seabbs Thanks, I think this provides a really nice building block, particularly with the README you've included.  I'll merge it here and explore a bit on some ideas for stacking on the ML and naming images in a way that seems sufficiently intuitive...

**Pull request merged**
